version: '3'

services:
  postgres:
    image: postgres
    container_name: my_postgres
    environment:
      POSTGRES_PASSWORD: Qaz123123
    volumes:
      - /docker-volumes2/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - MyPG_Network

networks:
  MyPG_Network:
    driver: bridge